### ISSUE TITLE
Send events via push notifications service

### ISSUE THREAD

**Issue by jensneuber** [trustlines-network/relay#112]
Use the firebase integration to push events

**Comment by berndbohmeier** [comment]
@jensneuber Do you need them as notification or as data message or as notification with some data payload? 
https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by jensneuber** [comment]
-> as notification with some data payload

**Comment by berndbohmeier** [comment]
Okay, so what should the title, body and data be. Is data just the event dict?

**Comment by berndbohmeier** [comment]
title for first iteration is "new <event name>", body is just "click for more details".
