### ISSUE TITLE
Revert upgrade to python 3.6

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/relay#172]
Sadly we have to revert the update to python 3.6 for now as the used gevent version 1.1 is to old (at least 1.2 is needed for python 3.6, see https://github.com/gevent/gevent/issues/903) but our old web3 v3 needs gevent < 1.2. 
To solve this in the future we need to upgrade web3 to v4.

**Comment by schmir** [comment]
Just out of curiosity: Why hasn't this been caught by travis?

**Comment by berndbohmeier** [comment]
The problem only shows up when calling the push notification API. We don't have tests for that.
