### ISSUE TITLE
Upgrade to web3 v4. 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/relay#173]
Ad web3 v3 is getting really old and is hindering us from switching to python 3.6, we should upgrade. 
See https://github.com/trustlines-network/relay/issues/172

**Comment by schmir** [comment]
eth-testrpc will not work with v4. We should probably use https://github.com/ethereum/eth-tester instead.

**Comment by schmir** [comment]
this is PR #190, the tests do pass but it still needs testing

**Comment by schmir** [comment]
this is done with 9ab257f5bebe02bdaf2a66005ce0730d73e7

We still need to get rid of some deprecation warnings. They changed how to call transact and call on a contract:
```
/home/ralf/local/lib/python3.6/site-packages/web3/utils/decorators.py:14: DeprecationWarning: call is deprecated in favor of contract.<functions/events>.<method name>.call
  return self.method(obj, *args, **kwargs)
```
