### ISSUE TITLE
refactor usage of time.time() calls inside graph related methods

### ISSUE THREAD

**Issue by schmir** [trustlines-network/relay#222]
`graph.py` calls `int(time.time())` extensively and uses the value to compute interests [1]. This frightens the life out of me: Some of the results it computes may be inconsistent in the sense that the values being computed have been computed at different times. It's a bit like having small random differences in our computations, which is probably not what we want. 

Unfortunately I didn't see this during code review.

The way to fix this is to call `time()` at the edges of our program and pass the time value into functions that need it. The edges in our case should be the REST API endpoints and each test function.

I'm looking a bit into implementing this for the path finding for closing a trustline.

[1] e.g. in 
```
_get_balance_with_interests_at_current_time
_get_capacity_at_current_time
```

**Comment by berndbohmeier** [comment]
I agree, I also wrote that we should do this in my PR, I only did not want to do it all in one go.

**Comment by schmir** [comment]
I think what remains to be done after https://github.com/trustlines-network/relay/pull/230 merged, is to make the remaining timestamp arguments mandatory and pass them from the tests and the REST API.
