### ISSUE TITLE
get_creditline is confusing

### ISSUE THREAD

**Issue by schmir** [trustlines-network/relay#223]
`trustline_data.get_creditline` is confusing (at least to me). It doesn't come with a docstring and it's neither called `get_creditline_received` nor `get_creditline_given`.

Same is also probably true for `get_interest_rate` and the setter functions.

**Comment by berndbohmeier** [comment]
`get_creditline(user, counterparty)` is the creditline given from user to conuterparty and you can get the received creditline with just switching the argument. I decided that for such low level functions I didnt want to have both. Do you think that is solved by documenting that?
If you think that is not clear, we can rename it into `get_creditline_given(user, counterparty)` and maybe also add `get_creditline_received(user, counter_party) = get_creditline_given(counter_party, user)`, but again, I dont know if we need that in that low abstraction.

**Comment by schmir** [comment]
I'm fine with having a docstring only.
