### ISSUE TITLE
Investigate why least_cost_path is considering the start node. 

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/relay#237]
Me and Come saw some strange behavior that the path finding will consider the edges leading back to the start node. So on a path A-B-C it does something like look at edge A-B and then try edge B-A. 
We should look into why if this is the case and if this is necessary or a problem.

**Comment by berndbohmeier** [comment]
@schmir Do you know why this is?

**Comment by schmir** [comment]
Hmm, I think this should not happen. 

https://github.com/trustlines-network/relay/blob/develop/relay/network_graph/alg.py#L87 should make the algorithm ignore these paths.

Do we have a test case?

**Comment by cducrest** [comment]
I don't believe the algorithm yields any wrong paths. I just observed that it will visit nodes more than once when computing the path, which is surprising and not coherent with Dijkstra's Algorithm (and probably not optimal).

**Comment by schmir** [comment]
here's dijkstra's algorithm as explained by himself: https://www-m3.ma.tum.de/foswiki/pub/MN0506/WebHome/dijkstra.pdf

**Comment by schmir** [comment]
ok, in order to clarify this a bit:
we could skip running the code block inside this loop by not considering `dst` nodes for which we already found a shortest path. At the moment these nodes are filtered out by the `if` statement at the end of the code block.

the ubergraph code probably does not do that, because they use a constant cost, and not a function.

It looks like it may make sense for us to implement it, though we don't have a good way to measure it.

```python
        for dst, edge_data in graph_adj[node].items():
            cost_from_start_to_dst = cost_fn(
                cost_from_start_to_node, node, dst, edge_data
            )
            if cost_from_start_to_dst is None:  # cost_fn decided this path is forbidden
                continue

            if max_cost is not None and max_cost < cost_from_start_to_dst:
                continue

            assert cost_from_start_to_dst >= cost_from_start_to_node

            least_cost_found_so_far_from_start_to_dst = least_costs.get(dst)
            if (
                least_cost_found_so_far_from_start_to_dst is None
                or cost_from_start_to_dst < least_cost_found_so_far_from_start_to_dst
            ):
                heapq.heappush(queue, (cost_from_start_to_dst, dst))
                least_costs[dst] = cost_from_start_to_dst
                backlinks[dst] = node

```
