### ISSUE TITLE
excessive log output "urllib3.connectionpool: Connection pool is full"

### ISSUE THREAD

**Issue by schmir** [trustlines-network/relay#246]
I've notived this while running the end2end tests. The relay server logs massive amounts of the below message. This may also point to a deeper problem of urllib3 (probably only when used with gevent).

I guess this started after the duplicate log output removal in e5840a6992415dffaa5e43452b28fb7cc131554

```
relay           | 2019-01-17T00:12:10.232426962Z 2019-01-17 00:12:10,232[WARNING] urllib3.connectionpool: Connection pool is full, discarding connection: node
relay           | 2019-01-17T00:12:10.367636890Z 2019-01-17 00:12:10,367[WARNING] urllib3.connectionpool: Connection pool is full, discarding connection: node
relay           | 2019-01-17T00:12:10.368289152Z 2019-01-17 00:12:10,368[WARNING] urllib3.connectionpool: Connection pool is full, discarding connection: node
relay           | 2019-01-17T00:12:10.369002609Z 2019-01-17 00:12:10,368[WARNING] urllib3.connectionpool: Connection pool is full, discarding connection: node
relay           | 2019-01-17T00:12:10.505551290Z 2019-01-17 00:12:10,505[WARNING] urllib3.connectionpool: Connection pool is full, discarding connection: node
```

**Comment by berndbohmeier** [comment]
I have never seen this running the e2e tests. Maybe its connected to the setup with the docker container.

**Comment by schmir** [comment]
I think the reason is that we changed how we setup the logging framework. My guess is that these have been logged before, but have never been shown. see e5840a6

**Comment by schmir** [comment]
I can confirm that the above mentioned commit is to blame.

**Comment by schmir** [comment]
warnings are silenced now as of 0fe02ca. I'm keeping this open, as we may look into it later.

**Comment by schmir** [comment]
#256 has amplified this problem. Therefore I'm closing it now.
