### ISSUE TITLE
RestAPI to deploy new identity contracts

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/relay#260]
There should be a rest API to ask for a deployment of a new identity contract. It should be possible to turn this on or off. 
First we should agree on how the endpoint should look like. 

Belongs to https://github.com/trustlines-network/project/issues/271

**Comment by schmir** [comment]
POST to `/api/v1/deploy-identity-contract` with `ownerAddress` as argument?

**Comment by berndbohmeier** [comment]
POST to /api/v1/identities with ownerAddress as json argument?

**Comment by berndbohmeier** [comment]
This follows more the idea of REST and will make more sense with GET requests later to 
`api/v1/identities/<identity_address>`

**Comment by schmir** [comment]
Given the fact, that we do have a bunch of POST requests that do not create any resources, I still think posting to `/deploy-identity-contract` is much clearer than posting to `/identities`.

From what I read we should also return 201 with a Location Header. I haven't implemented this in PR  #267

This reminded me of the 'kingdom of nouns' blog post: https://steve-yegge.blogspot.com/2006/03/execution-in-kingdom-of-nouns.html

**Comment by berndbohmeier** [comment]
201 with location header sounds good.
Which endpoints do we have that use POST but don't create resources? Maybe can fix them.

**Comment by schmir** [comment]
why do you think they are broken? because we don't adhere to some 'REST way', that's not even clearly defined? I fail to see the benefits of changing anything here just for the sake of it.

**Comment by berndbohmeier** [comment]
They are broken if they dont work in the expected way. The advantage from REST is that they are self documenting and easy to navigate if they are properly implemented. 

If you know the endpoint to look up identities GET `/identities`, you know how to create a new (POST `/identities`, how to look up a specific one (GET `/identities/<identifier>) and so on. 

If you do POST with function names there is now way, it is just a bunch of random function names. 
(`deployIdentityContract`? `createIdentityContract`? `deployIdentity`?)

**Comment by schmir** [comment]
I think if we want to fix them in the way you describe,we should look at something that supports swagger out-of-the-box.
I do not know if that effort would  pay off though, since what we have now, seems to work for us without problems.

**Comment by berndbohmeier** [comment]
yes, I would not look into it right now, but there is the option to switch to https://flask-restplus.readthedocs.io/en/stable/, which comes with swagger support and is really similar to the resful flask we use.

**Comment by berndbohmeier** [comment]
I guess this is done
