### ISSUE TITLE
REST api for meta tx infos

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/relay#266]
Similar to how we have an endpoint to get informations on current gas price and nonce we should have an endpoint like that for meta transaction. So far this would only include the meta transaction nonce.

**Comment by schmir** [comment]
It's unclear to me what this issue is about. Can you be a bit more specific?

**Comment by berndbohmeier** [comment]
We need an endpoint similar to https://github.com/trustlines-network/relay/blob/develop/docs/RelayAPI.md#transaction-infos-for-user
to get the next nonce from the relay server to prepare the meta transaction in the client,  and later maybe the gas cost set by the delegator.  

Possible endpoints 
- reuse the one we have 
- use something like `/identities/<address>` and there return infos about the identity contract including the last used nonce.
- use a dedicated endpoint, somthing like `/meta-transaction-infos/<address` where we also later would make the gasPrice set by the delegator available.

**Comment by schmir** [comment]
ok, thanks for the clarification. I would choose the second option.

**Comment by berndbohmeier** [comment]
okay
