### ISSUE TITLE
Endpoint for event updates

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/relay#31]
Create an endpoint to get a stream of events that happen to the user at the moment. 
- [x] Define Events that can happen 
- [x] Define endpoint

**Comment by jensneuber** [comment]
What we came up with: 

- We agreed to use the websocket protocol for the streams
- two streams are needed
   1. one is dedicated for events that occur / can be found on the blockchain -> event_stream
   2. one for user to user messaging, that is relayed -> message_stream
- the event_stream is a "rich" stream, meaning all/some values of the events are included

Addition: 
- a list of events that should appear on the event_stream
   - creditline updates & creditline update requests
   - transfers

Questions:
- should we update the balance via stream as well? or use the events described above to trigger a fetch

**Comment by berndbohmeier** [comment]
Done
