### ISSUE TITLE
Endpoint for maximum transferable amount

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/relay#34]
We want to have an endpoint that a user can query to ask for the maximum amount he can sent to a specific user address. This must take into account the fees and the value of the transfer of every edge. 

- [x] implement path finding in graph + tests
- [ ] implement REST endpoint

and if you want a written proof why this is indeed the maximum value?

**Comment by cducrest** [comment]
You want the maximum amounts he can transfer in ONE transaction or using as many transaction as needed?

**Comment by berndbohmeier** [comment]
MMh. I was think of in ONE transaction, but also the other would make sense. 
First is helpful when someone would like to put in a value for a transfer that will not fail, second would help to see how good the connection to a certain person is. I would say atm the first is more important, so maybe start with the first and later the second?

**Comment by cducrest** [comment]
I cannot do this deterministically in a reasonable computational time, for I am confronted to the same problems as for triangulation (that is the fee function not being bijective and sender paying for the fees) if I want to return the `max value` for the transaction, and not `max value + fees`. 

Imagine the trustlines `A<->B`, where A can owe 101 to B, with a fee of 1%. I can say B can receive 101, and A can send 101 to B, but this is `value + fee` and cannot tell A what max value he can send. (in that case he will have to enter a `value = 99 ` to send, and then `value + fee = 100`)

Are we interested in getting an estimation of the `value`, or the exact amount of `value + fees`?

**Comment by cducrest** [comment]
done
