### ISSUE TITLE
Onboarder creates UserProxy and Controller for Onboarded

### ISSUE THREAD

**Issue by ice09** [trustlines-network/relay#4]
The relay server API must support the creation of the UserProxy and Controller by the onboarder. 

This function will be called by the onboarder and creates a UserProxy for the onboarded and initializes this proxy with the address of the onboarded.

see https://github.com/trustlines-network/contracts/issues/24

**Comment by berndbohmeier** [comment]
This can not be done by the relay server, it can only relay the transaction using the relay endpoint. It must be implemented by the clientlib
