### ISSUE TITLE
Query the imbalance fee

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-network/relay#49]
At the moment the imbalance fee is just given as a constant to the network graph. It needs to query it in case the network was not deployed with the default value. 
- [ ] Method to query value from blockchain in currency_network_proxy
- [ ] Use method on graph setup

**Comment by cducrest** [comment]
Do we need to add a getter for "capacityImbalanceFeeDivisor" in "contracts/contracts/CurrencyNetwork.sol" to do that?

**Comment by berndbohmeier** [comment]
Solidity creates automatically getters for public variables. But unfortunately I apparently made it internal, shit. The fix is to make that variable public.

**Comment by schmir** [comment]
implemented in 962f610fc629ae15ccbc45a6
