### ISSUE TITLE
Endpoint for wrapped ETH balance

### ISSUE THREAD

**Issue by dakingha69** [trustlines-network/relay#67]
We need an endpoint for retrieving the balance of wrapped ETH of an user. I am not sure though how the endpoint should be named. I think something like `users/:userAddress/balances/:ethTokenAddress` could be the most consistent regarding our existing endpoints. Or maybe even use `users/:userAddress/balances` and return an object? @berndbohmeier what do you think?

**Comment by berndbohmeier** [comment]
what about tokens/:tokenAdress/users/:userAddress/balance

**Comment by berndbohmeier** [comment]
To be consistent with networks/:networkAddress/users..
@dakingha69

**Comment by dakingha69** [comment]
ah yea `/tokens/:tokenAddress/users/:userAddress/balance` makes more sense. but then we should also add the address of the eth wrapper contract to the endpoint `/tokens` instead of `/exchange/eth`

**Comment by berndbohmeier** [comment]
Yes, but maybe also leave it there, because it is still a special token.
