### ISSUE TITLE
streams.Subject.publish will skip subscriptions

### ISSUE THREAD

**Issue by schmir** [trustlines-network/relay#85]
Subject.publish iterates over self.subscriptions. It calls Subscription.notify for every subscription.

If a DisconnectedError occurs, notify tries to remove the subscription, which modifies the list we're iterating over.

I'd say either copy the list or remove the subscriptions after iteration is over.

**Comment by berndbohmeier** [comment]
Ah, good catch. Any design idea to prevent that kind of errors in the future?
When I got it right a copy at https://github.com/trustlines-network/relay/blob/develop/relay/streams.py#L43 would be sufficient?  Can you add a test that triggers this bug and confirms this is fixed?

**Comment by berndbohmeier** [comment]
Ideally the client should disconnect already when the websocket lib detects a disconnect (https://github.com/trustlines-network/relay/blob/develop/relay/api/streams/transport.py#L46). This is not implemented yet, but I'll open an issue.

**Comment by schmir** [comment]
> Any design idea to prevent that kind of errors in the future?

1. Don't mutate things that you're iterating over
2. As a more general rule don't mutate things
3. Use a language that doesn't allow you to mutate things (or rather that allows you to mutate things in a controlled way).

I don't see a good way to prevent such errors in a general way when using python.

Copying the list is not  enough - at least when you want to be kind to your coworkers. It must have a comment too.

**Comment by schmir** [comment]
Another problem might be when the client throws other exceptions that are not being caught. Then the rest of the client in the list don't get notified.

**Comment by berndbohmeier** [comment]
But at least we would be aware of that because it would bubble up right? 
Now catching all exception doesn't seem the right way to me. 

Not knowing which exception might happen when calling a function is btw my most hated it about Python.

**Comment by schmir** [comment]
> But at least we would be aware of that because it would bubble up right?

I'm not sure. Do we have to manually watch the logs for that? I've used sentry for error reporting in the past. Maybe that would also be a good fit here.

> Now catching all exception doesn't seem the right way to me.

Catching and reporting. At the end of the day it's a better experience for the user if their events are not getting lost.

> Not knowing which exception might happen when calling a function is btw my most hated part about Python.

Checked exceptions in Java are also considered a mistake by some people (me included). But the fact that you don't know which exceptions can be raised, might be a good reason to catch them, report them, and make the code not bail out, but deliver the events. Even more so since this has been a real issue.

**Comment by berndbohmeier** [comment]
> I'm not sure. Do we have to manually watch the logs for that? I've used sentry for error reporting in the past. Maybe that would also be a good fit here. 

yes, at the moment we do. And it is a pain because we get a lot of depricated warnings from the libraries. We need to solve that and use something like what you mentioned for reporting. I have no opinion on that in the moment, so if you think that is a good fit, go ahead. 

> Catching and reporting. At the end of the day it's a better experience for the user if their events are not getting lost.

Okay.

**Comment by berndbohmeier** [comment]
Done
