### ISSUE TITLE
Fees for single-hop transfer / last hop of a multi-hop transfer

### ISSUE THREAD

**Issue by cducrest** [trustlines-network/relay#97]
Does it make sense to have fees in a single-hop transfer or the last-hop of a mediated transfer? If Alice wants to send Bob 100, she will instead pay 100 + fees and Bob will receive 100 + fees, for single hop. It seems counter intuitive, even though I understand the reason behind the existence of fees.

For multi-hop transfers, the question is the same: the user cannot fix the value he wants to send or the value the receiver has to receive. Fees will always make this value fluctuate.

**Comment by berndbohmeier** [comment]
So you propose to drop the fee for the last edge?

**Comment by cducrest** [comment]
Yes, I just think it makes sense that when you enter a value of x for a transaction, either x has to be spent (make receiver pay for fees) or x has to be received (drop fees for last edge).

**Comment by berndbohmeier** [comment]
Okay. But that means that receivers are not paid for the capacity they provide and the sender does not have to pay for that imbalance. I also see it in a way that it right now kind of is an instant interest payed for the risk the receivers has. You would argue those things are less important then receiving the right amount?

**Comment by cducrest** [comment]
I would tend to say that receivers do not provide capacity, as they are somewhat "actively" using the system by receiving money (i.e. they likely asked to receive money). I think the system should be agnostic of risk, for users should know the reliance on trust of the application and take into account trust when they establish trustlines, not when they receive IOUs.

It would make sense that either the sender pays more than "value" or the receiver receives less, to represent capacity / unbalance fee. But this mix we do is super counter-intuitive for me.

**Comment by heikoheiko** [comment]
Two notes:
1) Fees are there to set economic incentives and the capacity fee especially to allow for a balanced network. If we don't have fees for the last edge, then the receiver might end receiving the value from a peer that is already indebted to him (increasing the imbalance), instead from one to whom he's indebted to (which would reduce imbalance). So the fees must also be calculated for the last edge. 

2) On the problem, that X+ is received, it's just a matter of interpretation. The receiver actually received two payments, one for the value, one for the fees in a single transfer. In the UI the fee component could be displayed separately.

**Comment by cducrest** [comment]
Decision was made to keep things like they currently are (fees are still paid for single-hop transfers and for the last hop of mediated transfers)
